name: Build and run tests

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
